import { TradeInput, computeTradeFields } from "./trade-utils";

function numOrNull(v: number | null | undefined | string): string | null {
  if (v === null || v === undefined || v === "") return null;
  const n = Number(v);
  return Number.isFinite(n) ? String(n) : null;
}

// Builds the full Drizzle insert/update value object from a TradeInput.
export function mapTradeValues(input: TradeInput) {
  const computed = computeTradeFields(input);

  const db = {
    date: new Date(input.date),
    time: input.time || "00:00",
    asset: input.asset,
    direction: input.direction,
    session: input.session || "Outro",
    sessionTimeStart: input.sessionTimeStart,
    sessionTimeEnd: input.sessionTimeEnd,
    timeframeEntry: input.timeframeEntry,
    timeframeContext: input.timeframeContext,
    setup: input.setup,
    entryPrice: numOrNull(input.entryPrice),
    stopLoss: numOrNull(input.stopLoss),
    takeProfit: numOrNull(input.takeProfit),
    positionSize: numOrNull(input.positionSize),
    accountBalanceAtTrade: numOrNull(input.accountBalanceAtTrade),
    riskPercent: input.riskPercent ?? null,
    riskAmount: computed.riskAmount != null ? String(computed.riskAmount) : null,
    plannedRR: computed.plannedRR,
    realizedRR: computed.realizedRR,
    resultAmount: String(input.resultAmount ?? 0),
    resultR: computed.resultR,
    resultPercent: computed.resultPercent,
    resultType: computed.resultType,
    htfBias: input.htfBias,
    ltfBias: input.ltfBias,
    liquidityType: input.liquidityType,
    liquiditySwept: input.liquiditySwept,
    bos: input.bos ?? false,
    choch: input.choch ?? false,
    fvg: input.fvg ?? false,
    orderBlock: input.orderBlock ?? false,
    breaker: input.breaker ?? false,
    sweepLiquidity: input.sweepLiquidity ?? false,
    displacement: input.displacement ?? false,
    trendConfirmation: input.trendConfirmation ?? false,
    amd: input.amd ?? false,
    premiumDiscount: input.premiumDiscount,
    macroEvent: input.macroEvent,
    macroCurrency: input.macroCurrency,
    macroImpact: input.macroImpact,
    macroBias: input.macroBias,
    followedPlan: input.followedPlan ?? true,
    earlyEntry: input.earlyEntry ?? false,
    earlyExit: input.earlyExit ?? false,
    revengeTrade: input.revengeTrade ?? false,
    fomo: input.fomo ?? false,
    overtrading: input.overtrading ?? false,
    emotionalBefore: input.emotionalBefore,
    emotionalAfter: input.emotionalAfter,
    mistakes: input.mistakes,
    whatWentRight: input.whatWentRight,
    whatWentWrong: input.whatWentWrong,
    lesson: input.lesson,
    notes: input.notes,
    screenshotUrl: input.screenshotUrl,
    preTradeScreenshotUrl: input.preTradeScreenshotUrl,
    postEntryScreenshotUrl: input.postEntryScreenshotUrl,
    postExitScreenshotUrl: input.postExitScreenshotUrl,
    dxyScreenshotUrl: input.dxyScreenshotUrl,
    status: (input.status as never) || "CLOSED",
    playbook: input.playbook,
    dxyBias: input.dxyBias,
    drawOnLiquidity: input.drawOnLiquidity,
    poi: input.poi,
    entryZone: input.entryZone,
    invalidation: input.invalidation,
    timeStop: input.timeStop,
    expectedSession: input.expectedSession,
    exitReason: input.exitReason,
    dxyHtfBias: input.dxyHtfBias,
    dxyH1Bias: input.dxyH1Bias,
    dxyLocation: input.dxyLocation,
    dxyLiquidityTarget: input.dxyLiquidityTarget,
    dxyConfirmation: input.dxyConfirmation,
    us02y: input.us02y,
    us10y: input.us10y,
    realYield: input.realYield,
    intermarketConfirm: input.intermarketConfirm,
    maeAmount: numOrNull(input.maeAmount),
    mfeAmount: numOrNull(input.mfeAmount),
    maePrice: numOrNull(input.maePrice),
    mfePrice: numOrNull(input.mfePrice),
    setupScore: input.setupScore ?? null,
    executionScore: input.executionScore ?? null,
    movedStopWithoutRule: input.movedStopWithoutRule ?? false,
    movedBeEarly: input.movedBeEarly ?? false,
    increasedRisk: input.increasedRisk ?? false,
    tradedDuringNews: input.tradedDuringNews ?? false,
    chasedPrice: input.chasedPrice ?? false,
    didNotWaitMss: input.didNotWaitMss ?? false,
    ignoredHtf: input.ignoredHtf ?? false,
    ignoredMacro: input.ignoredMacro ?? false,
    ignoredDxy: input.ignoredDxy ?? false,
    tradedOutOfSession: input.tradedOutOfSession ?? false,
    tradedOutsidePlan: input.tradedOutsidePlan ?? false,
    unrealizedPnl: numOrNull(input.unrealizedPnl),
    isDemo: input.isDemo ?? false,
  } as never;

  return { db, computed };
}
