export interface Trade {
  id: number;
  createdAt: string;
  date: string;
  time: string;
  asset: string;
  direction: "BUY" | "SELL";
  session: string;
  timeframeEntry?: string;
  timeframeContext?: string;
  setup?: string;
  entryPrice?: number;
  stopLoss?: number;
  takeProfit?: number;
  positionSize?: number;
  accountBalanceAtTrade?: number;
  riskPercent?: number;
  riskAmount?: number;
  plannedRR?: number;
  realizedRR?: number;
  resultAmount?: number;
  resultR?: number;
  resultPercent?: number;
  resultType: "WIN" | "LOSS" | "BREAK EVEN";
  htfBias?: string;
  ltfBias?: string;
  liquidityType?: string;
  liquiditySwept?: string;
  bos?: boolean;
  choch?: boolean;
  fvg?: boolean;
  orderBlock?: boolean;
  breaker?: boolean;
  sweepLiquidity?: boolean;
  displacement?: boolean;
  trendConfirmation?: boolean;
  amd?: boolean;
  premiumDiscount?: string;
  macroEvent?: string;
  macroCurrency?: string;
  macroImpact?: string;
  macroBias?: string;
  followedPlan?: boolean;
  earlyEntry?: boolean;
  earlyExit?: boolean;
  revengeTrade?: boolean;
  fomo?: boolean;
  overtrading?: boolean;
  emotionalBefore?: string;
  emotionalAfter?: string;
  mistakes?: string;
  whatWentRight?: string;
  whatWentWrong?: string;
  lesson?: string;
  notes?: string;
  screenshotUrl?: string;
  preTradeScreenshotUrl?: string;
  postEntryScreenshotUrl?: string;
  postExitScreenshotUrl?: string;
  dxyScreenshotUrl?: string;
  status?: "WATCHLIST" | "PLANNED" | "WAITING_TRIGGER" | "READY" | "OPEN" | "CLOSED" | "CANCELLED";
  playbook?: string;
  dxyBias?: string;
  drawOnLiquidity?: string;
  poi?: string;
  entryZone?: string;
  invalidation?: string;
  timeStop?: string;
  expectedSession?: string;
  exitReason?: string;
  dxyHtfBias?: string;
  dxyH1Bias?: string;
  dxyLocation?: string;
  dxyLiquidityTarget?: string;
  dxyConfirmation?: string;
  us02y?: string;
  us10y?: string;
  realYield?: string;
  intermarketConfirm?: string;
  maeAmount?: number;
  mfeAmount?: number;
  maePrice?: number;
  mfePrice?: number;
  setupScore?: number;
  executionScore?: number;
  movedStopWithoutRule?: boolean;
  movedBeEarly?: boolean;
  increasedRisk?: boolean;
  tradedDuringNews?: boolean;
  chasedPrice?: boolean;
  didNotWaitMss?: boolean;
  ignoredHtf?: boolean;
  ignoredMacro?: boolean;
  ignoredDxy?: boolean;
  tradedOutOfSession?: boolean;
  tradedOutsidePlan?: boolean;
  unrealizedPnl?: number;
  isDemo?: boolean;
}

export interface Config {
  initialCapital: number;
  riskPerTrade: number;
  riskPercent: number;
  dailyGoal: number;
  dailyLossLimit: number;
  maxDrawdown: number;
  currency: string;
  accountName: string;
  sessionAsiaStart: string;
  sessionAsiaEnd: string;
  sessionLondonStart: string;
  sessionLondonEnd: string;
  sessionNYStart: string;
  sessionNYEnd: string;
  // Account source of truth
  totalDeposits: number;
  totalWithdrawals: number;
  // Risk engine limits
  weeklyRiskLimit: number;
  monthlyDrawdownLimit: number;
  maxOpenRisk: number;
  maxCorrelatedExposure: number;
  maxTradesPerDay: number;
  // Statistics thresholds
  sampleSizeWarning: number;
  sampleSizeLow: number;
  // Appearance (synced with localStorage)
  theme: "dark" | "light" | "system";
  accentColor: "green" | "blue" | "purple" | "cyan";
  density: "compact" | "comfortable";
}
