export interface Trade {
  id: number;
  createdAt: string;
  date: string;
  time: string;
  asset: string;
  direction: "BUY" | "SELL";
  session: string;
  timeframeEntry?: string;
  timeframeContext?: string;
  setup?: string;
  entryPrice?: number;
  stopLoss?: number;
  takeProfit?: number;
  positionSize?: number;
  accountBalanceAtTrade?: number;
  riskPercent?: number;
  riskAmount?: number;
  plannedRR?: number;
  realizedRR?: number;
  resultAmount?: number;
  resultR?: number;
  resultPercent?: number;
  resultType: "WIN" | "LOSS" | "BREAK EVEN";
  htfBias?: string;
  ltfBias?: string;
  liquidityType?: string;
  liquiditySwept?: string;
  bos?: boolean;
  choch?: boolean;
  fvg?: boolean;
  orderBlock?: boolean;
  breaker?: boolean;
  sweepLiquidity?: boolean;
  displacement?: boolean;
  trendConfirmation?: boolean;
  amd?: boolean;
  premiumDiscount?: string;
  macroEvent?: string;
  macroCurrency?: string;
  macroImpact?: string;
  macroBias?: string;
  followedPlan?: boolean;
  earlyEntry?: boolean;
  earlyExit?: boolean;
  revengeTrade?: boolean;
  fomo?: boolean;
  overtrading?: boolean;
  emotionalBefore?: string;
  emotionalAfter?: string;
  mistakes?: string;
  whatWentRight?: string;
  whatWentWrong?: string;
  lesson?: string;
  notes?: string;
  screenshotUrl?: string;
  isDemo?: boolean;
}

export interface Config {
  initialCapital: number;
  riskPerTrade: number;
  riskPercent: number;
  dailyGoal: number;
  dailyLossLimit: number;
  maxDrawdown: number;
  currency: string;
  accountName: string;
  sessionAsiaStart: string;
  sessionAsiaEnd: string;
  sessionLondonStart: string;
  sessionLondonEnd: string;
  sessionNYStart: string;
  sessionNYEnd: string;
}
