import {
  pgTable,
  serial,
  text,
  timestamp,
  boolean,
  decimal,
  integer,
  real,
} from "drizzle-orm/pg-core";

export const trades = pgTable("trades", {
  id: serial("id").primaryKey(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  date: timestamp("date").notNull(),
  time: text("time").notNull(),
  asset: text("asset").notNull(),
  direction: text("direction").notNull(), // BUY / SELL
  session: text("session").notNull(), // Ásia, Londres, Nova York, Outro
  sessionTimeStart: text("session_time_start"),
  sessionTimeEnd: text("session_time_end"),
  timeframeEntry: text("timeframe_entry"),
  timeframeContext: text("timeframe_context"),
  setup: text("setup"),
  entryPrice: decimal("entry_price", { precision: 18, scale: 8 }),
  stopLoss: decimal("stop_loss", { precision: 18, scale: 8 }),
  takeProfit: decimal("take_profit", { precision: 18, scale: 8 }),
  positionSize: decimal("position_size", { precision: 18, scale: 8 }),
  accountBalanceAtTrade: decimal("account_balance_at_trade", { precision: 18, scale: 8 }),
  riskPercent: real("risk_percent"),
  riskAmount: decimal("risk_amount", { precision: 18, scale: 8 }),
  plannedRR: real("planned_rr"),
  realizedRR: real("realized_rr"),
  resultAmount: decimal("result_amount", { precision: 18, scale: 8 }),
  resultR: real("result_r"),
  resultPercent: real("result_percent"),
  resultType: text("result_type"), // WIN / LOSS / BREAK EVEN
  htfBias: text("htf_bias"),
  ltfBias: text("ltf_bias"),
  liquidityType: text("liquidity_type"),
  liquiditySwept: text("liquidity_swept"),
  bos: boolean("bos").default(false),
  choch: boolean("choch").default(false),
  fvg: boolean("fvg").default(false),
  orderBlock: boolean("order_block").default(false),
  breaker: boolean("breaker").default(false),
  sweepLiquidity: boolean("sweep_liquidity").default(false),
  displacement: boolean("displacement").default(false),
  trendConfirmation: boolean("trend_confirmation").default(false),
  amd: boolean("amd").default(false),
  premiumDiscount: text("premium_discount"),
  macroEvent: text("macro_event"),
  macroCurrency: text("macro_currency"),
  macroImpact: text("macro_impact"), // Baixo, Médio, Alto
  macroBias: text("macro_bias"), // Bullish, Bearish, Neutro
  followedPlan: boolean("followed_plan"),
  earlyEntry: boolean("early_entry").default(false),
  earlyExit: boolean("early_exit").default(false),
  revengeTrade: boolean("revenge_trade").default(false),
  fomo: boolean("fomo").default(false),
  overtrading: boolean("overtrading").default(false),
  emotionalBefore: text("emotional_before"),
  emotionalAfter: text("emotional_after"),
  mistakes: text("mistakes"),
  whatWentRight: text("what_went_right"),
  whatWentWrong: text("what_went_wrong"),
  lesson: text("lesson"),
  notes: text("notes"),
  screenshotUrl: text("screenshot_url"),
  preTradeScreenshotUrl: text("pre_trade_screenshot_url"),
  postEntryScreenshotUrl: text("post_entry_screenshot_url"),
  postExitScreenshotUrl: text("post_exit_screenshot_url"),
  dxyScreenshotUrl: text("dxy_screenshot_url"),

  // Planning / lifecycle
  status: text("status").notNull().default("CLOSED"), // WATCHLIST, PLANNED, WAITING_TRIGGER, READY, OPEN, CLOSED, CANCELLED
  playbook: text("playbook"),
  dxyBias: text("dxy_bias"),
  drawOnLiquidity: text("draw_on_liquidity"),
  poi: text("poi"),
  entryZone: text("entry_zone"),
  invalidation: text("invalidation"),
  timeStop: text("time_stop"),
  expectedSession: text("expected_session"),
  exitReason: text("exit_reason"),

  // Intermarket
  dxyHtfBias: text("dxy_htf_bias"),
  dxyH1Bias: text("dxy_h1_bias"),
  dxyLocation: text("dxy_location"),
  dxyLiquidityTarget: text("dxy_liquidity_target"),
  dxyConfirmation: text("dxy_confirmation"),
  us02y: text("us02y"),
  us10y: text("us10y"),
  realYield: text("real_yield"),
  intermarketConfirm: text("intermarket_confirm"),

  // MAE / MFE
  maeAmount: decimal("mae_amount", { precision: 18, scale: 8 }),
  mfeAmount: decimal("mfe_amount", { precision: 18, scale: 8 }),
  maePrice: decimal("mae_price", { precision: 18, scale: 8 }),
  mfePrice: decimal("mfe_price", { precision: 18, scale: 8 }),

  // Scores
  setupScore: integer("setup_score"),
  executionScore: integer("execution_score"),

  // Discipline flags
  movedStopWithoutRule: boolean("moved_stop_without_rule").default(false),
  movedBeEarly: boolean("moved_be_early").default(false),
  increasedRisk: boolean("increased_risk").default(false),
  tradedDuringNews: boolean("traded_during_news").default(false),
  chasedPrice: boolean("chased_price").default(false),
  didNotWaitMss: boolean("did_not_wait_mss").default(false),
  ignoredHtf: boolean("ignored_htf").default(false),
  ignoredMacro: boolean("ignored_macro").default(false),
  ignoredDxy: boolean("ignored_dxy").default(false),
  tradedOutOfSession: boolean("traded_out_of_session").default(false),
  tradedOutsidePlan: boolean("traded_outside_plan").default(false),

  unrealizedPnl: decimal("unrealized_pnl", { precision: 18, scale: 8 }),

  isDemo: boolean("is_demo").default(false),
});

export const config = pgTable("config", {
  id: serial("id").primaryKey(),
  key: text("key").notNull().unique(),
  value: text("value").notNull(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const macroCards = pgTable("macro_cards", {
  id: serial("id").primaryKey(),
  currency: text("currency").notNull().unique(),
  bias: text("bias").notNull().default("Neutro"),
  score: integer("score").notNull().default(0),
  inflation: text("inflation").default("Neutral"),
  employment: text("employment").default("Neutral"),
  activity: text("activity").default("Neutral"),
  centralBank: text("central_bank").default("Neutral"),
  yieldDirection: text("yield_direction").default("Neutral"),
  dxy: text("dxy").default("Neutral"),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const dailyBias = pgTable("daily_bias", {
  id: serial("id").primaryKey(),
  date: text("date").notNull(),
  currency: text("currency").notNull(),
  session: text("session"),
  inflation: text("inflation").default("Neutral"),
  employment: text("employment").default("Neutral"),
  activity: text("activity").default("Neutral"),
  centralBank: text("central_bank").default("Neutral"),
  yields: text("yields").default("Neutral"),
  dxy: text("dxy").default("Neutral"),
  biasFinal: text("bias_final").default("Neutro"),
  conviction: integer("conviction").default(5),
  thesis: text("thesis"),
  invalidation: text("invalidation"),
  dxyActual: text("dxy_actual"),
  thesisResult: text("thesis_result"),
  createdAt: timestamp("created_at").defaultNow(),
});
