import {
  pgTable,
  serial,
  text,
  timestamp,
  boolean,
  decimal,
  integer,
  real,
} from "drizzle-orm/pg-core";

export const trades = pgTable("trades", {
  id: serial("id").primaryKey(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  date: timestamp("date").notNull(),
  time: text("time").notNull(),
  asset: text("asset").notNull(),
  direction: text("direction").notNull(), // BUY / SELL
  session: text("session").notNull(), // Ásia, Londres, Nova York, Outro
  sessionTimeStart: text("session_time_start"),
  sessionTimeEnd: text("session_time_end"),
  timeframeEntry: text("timeframe_entry"),
  timeframeContext: text("timeframe_context"),
  setup: text("setup"),
  entryPrice: decimal("entry_price", { precision: 18, scale: 8 }),
  stopLoss: decimal("stop_loss", { precision: 18, scale: 8 }),
  takeProfit: decimal("take_profit", { precision: 18, scale: 8 }),
  positionSize: decimal("position_size", { precision: 18, scale: 8 }),
  accountBalanceAtTrade: decimal("account_balance_at_trade", { precision: 18, scale: 8 }),
  riskPercent: real("risk_percent"),
  riskAmount: decimal("risk_amount", { precision: 18, scale: 8 }),
  plannedRR: real("planned_rr"),
  realizedRR: real("realized_rr"),
  resultAmount: decimal("result_amount", { precision: 18, scale: 8 }),
  resultR: real("result_r"),
  resultPercent: real("result_percent"),
  resultType: text("result_type"), // WIN / LOSS / BREAK EVEN
  htfBias: text("htf_bias"),
  ltfBias: text("ltf_bias"),
  liquidityType: text("liquidity_type"),
  liquiditySwept: text("liquidity_swept"),
  bos: boolean("bos").default(false),
  choch: boolean("choch").default(false),
  fvg: boolean("fvg").default(false),
  orderBlock: boolean("order_block").default(false),
  breaker: boolean("breaker").default(false),
  sweepLiquidity: boolean("sweep_liquidity").default(false),
  displacement: boolean("displacement").default(false),
  trendConfirmation: boolean("trend_confirmation").default(false),
  amd: boolean("amd").default(false),
  premiumDiscount: text("premium_discount"),
  macroEvent: text("macro_event"),
  macroCurrency: text("macro_currency"),
  macroImpact: text("macro_impact"), // Baixo, Médio, Alto
  macroBias: text("macro_bias"), // Bullish, Bearish, Neutro
  followedPlan: boolean("followed_plan"),
  earlyEntry: boolean("early_entry").default(false),
  earlyExit: boolean("early_exit").default(false),
  revengeTrade: boolean("revenge_trade").default(false),
  fomo: boolean("fomo").default(false),
  overtrading: boolean("overtrading").default(false),
  emotionalBefore: text("emotional_before"),
  emotionalAfter: text("emotional_after"),
  mistakes: text("mistakes"),
  whatWentRight: text("what_went_right"),
  whatWentWrong: text("what_went_wrong"),
  lesson: text("lesson"),
  notes: text("notes"),
  screenshotUrl: text("screenshot_url"),
  isDemo: boolean("is_demo").default(false),
});

export const config = pgTable("config", {
  id: serial("id").primaryKey(),
  key: text("key").notNull().unique(),
  value: text("value").notNull(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
